import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

export type AiProvider =
  | "google"
  | "openai"
  | "anthropic"
  | "openai-compatible";

export type RuntimeConfig = {
  triggerSecretKey: string;
  triggerProjectRef: string;
  clickhouseUrl: string;
  clickhouseUser: string;
  clickhousePassword: string;
  clickhouseDatabase: string;
  orsApiKey: string;
  aiProvider: AiProvider;
  aiApiKey: string;
  aiModel: string;
  /** For Ollama / LM Studio / other OpenAI-compatible servers. */
  aiBaseUrl: string;
  updatedAt?: string;
};

export const EMPTY_RUNTIME_CONFIG: RuntimeConfig = {
  triggerSecretKey: "",
  triggerProjectRef: "",
  clickhouseUrl: "",
  clickhouseUser: "default",
  clickhousePassword: "",
  clickhouseDatabase: "default",
  orsApiKey: "",
  aiProvider: "google",
  aiApiKey: "",
  aiModel: "gemini-flash-latest",
  aiBaseUrl: "http://127.0.0.1:1234/v1",
};

const CONFIG_DIR = join(process.cwd(), ".data");
const CONFIG_PATH = join(CONFIG_DIR, "runtime-config.json");

export function maskSecret(value: string): string {
  if (!value) return "";
  if (value.length <= 8) return "••••";
  return `${value.slice(0, 3)}…${value.slice(-4)}`;
}

export function readRuntimeConfig(): RuntimeConfig {
  try {
    if (!existsSync(CONFIG_PATH)) return { ...EMPTY_RUNTIME_CONFIG };
    const raw = readFileSync(CONFIG_PATH, "utf8");
    const parsed = JSON.parse(raw) as Partial<RuntimeConfig>;
    return { ...EMPTY_RUNTIME_CONFIG, ...parsed };
  } catch {
    return { ...EMPTY_RUNTIME_CONFIG };
  }
}

export function writeRuntimeConfig(patch: Partial<RuntimeConfig>): RuntimeConfig {
  const current = readRuntimeConfig();
  const next: RuntimeConfig = {
    ...current,
    ...patch,
    updatedAt: new Date().toISOString(),
  };
  if (!existsSync(CONFIG_DIR)) mkdirSync(CONFIG_DIR, { recursive: true });
  writeFileSync(CONFIG_PATH, JSON.stringify(next, null, 2), "utf8");
  applyRuntimeConfigToEnv(next);
  syncEnvLocal(next);
  return next;
}

/** Push BYOK values into process.env for this Node process (Next server / Trigger import). */
export function applyRuntimeConfigToEnv(config = readRuntimeConfig()): void {
  if (config.triggerSecretKey) {
    process.env.TRIGGER_SECRET_KEY = config.triggerSecretKey;
  }
  if (config.triggerProjectRef) {
    process.env.TRIGGER_PROJECT_REF = config.triggerProjectRef;
  }
  if (config.clickhouseUrl) {
    process.env.CLICKHOUSE_URL = config.clickhouseUrl;
    process.env.CLICKHOUSE_HOST = config.clickhouseUrl;
  }
  if (config.clickhouseUser) process.env.CLICKHOUSE_USER = config.clickhouseUser;
  if (config.clickhousePassword !== undefined) {
    process.env.CLICKHOUSE_PASSWORD = config.clickhousePassword;
  }
  if (config.clickhouseDatabase) {
    process.env.CLICKHOUSE_DATABASE = config.clickhouseDatabase;
  }
  if (config.orsApiKey) process.env.ORS_API_KEY = config.orsApiKey;

  if (config.aiApiKey) {
    switch (config.aiProvider) {
      case "google":
        process.env.GOOGLE_GENERATIVE_AI_API_KEY = config.aiApiKey;
        break;
      case "openai":
        process.env.OPENAI_API_KEY = config.aiApiKey;
        break;
      case "anthropic":
        process.env.ANTHROPIC_API_KEY = config.aiApiKey;
        break;
      case "openai-compatible":
        process.env.OPENAI_API_KEY = config.aiApiKey || "local";
        process.env.OPENAI_BASE_URL = config.aiBaseUrl;
        break;
      default: {
        const _exhaustive: never = config.aiProvider;
        void _exhaustive;
      }
    }
  }
  if (config.aiModel) {
    process.env.CYCLEFORGE_AI_MODEL = config.aiModel;
    if (config.aiProvider === "google") {
      process.env.GOOGLE_GENERATIVE_AI_MODEL = config.aiModel;
    }
  }
  if (config.aiBaseUrl) process.env.CYCLEFORGE_AI_BASE_URL = config.aiBaseUrl;
  process.env.CYCLEFORGE_AI_PROVIDER = config.aiProvider;
}

function syncEnvLocal(config: RuntimeConfig): void {
  try {
    const envPath = join(process.cwd(), ".env.local");
    const lines = [
      "# Generated by CycleForge Setup UI — do not commit secrets.",
      config.triggerSecretKey
        ? `TRIGGER_SECRET_KEY=${config.triggerSecretKey}`
        : null,
      config.triggerProjectRef
        ? `TRIGGER_PROJECT_REF=${config.triggerProjectRef}`
        : null,
      config.clickhouseUrl ? `CLICKHOUSE_URL=${config.clickhouseUrl}` : null,
      config.clickhouseUser ? `CLICKHOUSE_USER=${config.clickhouseUser}` : null,
      config.clickhousePassword !== ""
        ? `CLICKHOUSE_PASSWORD=${config.clickhousePassword}`
        : null,
      config.clickhouseDatabase
        ? `CLICKHOUSE_DATABASE=${config.clickhouseDatabase}`
        : null,
      config.orsApiKey ? `ORS_API_KEY=${config.orsApiKey}` : null,
      config.aiProvider === "google" && config.aiApiKey
        ? `GOOGLE_GENERATIVE_AI_API_KEY=${config.aiApiKey}`
        : null,
      config.aiProvider === "google" && config.aiModel
        ? `GOOGLE_GENERATIVE_AI_MODEL=${config.aiModel}`
        : null,
      config.aiProvider === "openai" && config.aiApiKey
        ? `OPENAI_API_KEY=${config.aiApiKey}`
        : null,
      config.aiProvider === "anthropic" && config.aiApiKey
        ? `ANTHROPIC_API_KEY=${config.aiApiKey}`
        : null,
      config.aiProvider === "openai-compatible"
        ? `OPENAI_API_KEY=${config.aiApiKey || "local"}`
        : null,
      config.aiProvider === "openai-compatible" && config.aiBaseUrl
        ? `OPENAI_BASE_URL=${config.aiBaseUrl}`
        : null,
      `CYCLEFORGE_AI_PROVIDER=${config.aiProvider}`,
      config.aiModel ? `CYCLEFORGE_AI_MODEL=${config.aiModel}` : null,
    ].filter(Boolean);

    // Merge with existing non-managed keys.
    let existing = "";
    if (existsSync(envPath)) existing = readFileSync(envPath, "utf8");
    const keep = existing
      .split("\n")
      .filter((line) => {
        const key = line.split("=")[0];
        if (!key || line.startsWith("#")) return false;
        return ![
          "TRIGGER_SECRET_KEY",
          "TRIGGER_PROJECT_REF",
          "CLICKHOUSE_URL",
          "CLICKHOUSE_HOST",
          "CLICKHOUSE_USER",
          "CLICKHOUSE_PASSWORD",
          "CLICKHOUSE_DATABASE",
          "ORS_API_KEY",
          "GOOGLE_GENERATIVE_AI_API_KEY",
          "GOOGLE_GENERATIVE_AI_MODEL",
          "OPENAI_API_KEY",
          "OPENAI_BASE_URL",
          "ANTHROPIC_API_KEY",
          "CYCLEFORGE_AI_PROVIDER",
          "CYCLEFORGE_AI_MODEL",
        ].includes(key);
      });
    writeFileSync(envPath, [...lines, "", ...keep].join("\n") + "\n", "utf8");
  } catch (err) {
    console.warn("syncEnvLocal failed", err);
  }
}

export function publicRuntimeConfig(config = readRuntimeConfig()) {
  return {
    triggerConfigured: Boolean(config.triggerSecretKey),
    triggerProjectRef: config.triggerProjectRef,
    triggerProjectRefMasked: maskSecret(config.triggerProjectRef),
    clickhouseConfigured: Boolean(config.clickhouseUrl),
    clickhouseUrlHost: config.clickhouseUrl
      ? config.clickhouseUrl.replace(/^https?:\/\//, "").split("/")[0]
      : "",
    clickhouseUrlMasked: maskSecret(config.clickhouseUrl),
    clickhouseUser: config.clickhouseUser,
    clickhouseUserMasked: maskSecret(config.clickhouseUser),
    clickhouseDatabase: config.clickhouseDatabase,
    clickhouseDatabaseMasked: maskSecret(config.clickhouseDatabase),
    orsConfigured: Boolean(config.orsApiKey),
    orsApiKeyMasked: maskSecret(config.orsApiKey),
    aiProvider: config.aiProvider,
    aiModel: config.aiModel,
    aiModelMasked: maskSecret(config.aiModel),
    aiBaseUrl: config.aiBaseUrl,
    aiConfigured: Boolean(
      config.aiApiKey ||
        (config.aiProvider === "openai-compatible" && config.aiBaseUrl),
    ),
    aiApiKeyMasked: maskSecret(config.aiApiKey),
    triggerSecretMasked: maskSecret(config.triggerSecretKey),
    clickhousePasswordSet: Boolean(config.clickhousePassword),
    updatedAt: config.updatedAt ?? null,
  };
}

/** Call once on server boot / first import. */
let applied = false;
export function ensureRuntimeConfigLoaded(): void {
  if (applied) return;
  applyRuntimeConfigToEnv();
  applied = true;
}
